package com.modpack.linktablet.client.ponder;

import com.modpack.linktablet.block.TabletBlockEntity;
import com.modpack.linktablet.frequency.SignalApp;
import com.simibubi.create.content.redstone.link.RedstoneLinkBlock;
import net.createmod.catnip.math.Pointing;
import net.createmod.ponder.api.scene.SceneBuilder;
import net.createmod.ponder.api.scene.SceneBuildingUtil;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.world.level.block.RedstoneLampBlock;

/**
 * Ponder storyboards for the Link Tablet. The schematic
 * ({@code ponder/tablet.nbt}, generated by the NbtTool scratch task)
 * holds a frequency-configured Redstone Link receiver, a lamp behind it,
 * and a floor-mounted tablet carrying the matching "Lamp" app.
 * <p>
 * Ponder levels don't run Create's link network, so the tap beat fakes
 * the response: app active → link POWERED → lamp LIT (Create's own link
 * scenes do the same).
 */
public class TabletScenes {

    public static void intro(SceneBuilder scene, SceneBuildingUtil util) {
        scene.title("tablet", "Controlling Redstone Links remotely");
        scene.configureBasePlate(0, 0, 5);
        scene.showBasePlate();
        scene.idle(5);

        BlockPos linkPos = util.grid().at(1, 1, 2);
        BlockPos lampPos = util.grid().at(1, 1, 3);
        BlockPos tabletPos = util.grid().at(3, 1, 2);

        scene.world().showSection(util.select().position(linkPos), Direction.DOWN);
        scene.world().showSection(util.select().position(lampPos), Direction.DOWN);
        scene.idle(10);
        scene.overlay().showText(60)
                .text("This Redstone Link receives on the frequency set by its two item slots")
                .attachKeyFrame()
                .pointAt(util.vector().topOf(linkPos))
                .placeNearTarget();
        scene.idle(70);

        scene.world().showSection(util.select().position(tabletPos), Direction.DOWN);
        scene.idle(10);
        scene.overlay().showText(70)
                .text("The Link Tablet holds apps: named switches that transmit on those same frequencies")
                .attachKeyFrame()
                .pointAt(util.vector().topOf(tabletPos))
                .placeNearTarget();
        scene.idle(80);

        scene.overlay().showControls(util.vector().topOf(tabletPos), Pointing.DOWN, 40).rightClick();
        scene.idle(20);
        setAppsActive(scene, tabletPos, true);
        scene.world().modifyBlock(linkPos,
                s -> s.setValue(RedstoneLinkBlock.POWERED, true), false);
        scene.world().modifyBlock(lampPos,
                s -> s.setValue(RedstoneLampBlock.LIT, true), false);
        scene.effects().indicateRedstone(linkPos);
        scene.idle(15);
        scene.overlay().showText(70)
                .text("Tapping an app on a mounted tablet's screen toggles every Link on its frequency")
                .attachKeyFrame()
                .pointAt(util.vector().topOf(tabletPos))
                .placeNearTarget();
        scene.idle(80);

        scene.overlay().showText(80)
                .text("Tip: right-click any Redstone Link while holding the tablet to add its frequency as an app")
                .attachKeyFrame()
                .pointAt(util.vector().topOf(linkPos))
                .placeNearTarget();
        scene.idle(90);

        scene.overlay().showControls(util.vector().topOf(tabletPos), Pointing.DOWN, 30).rightClick();
        scene.idle(15);
        setAppsActive(scene, tabletPos, false);
        scene.world().modifyBlock(linkPos,
                s -> s.setValue(RedstoneLinkBlock.POWERED, false), false);
        scene.world().modifyBlock(lampPos,
                s -> s.setValue(RedstoneLampBlock.LIT, false), false);
        scene.idle(20);
        scene.markAsFinished();
    }

    /** Flips every app on the scene tablet; setApps also updates LIT. */
    private static void setAppsActive(SceneBuilder scene, BlockPos pos, boolean active) {
        scene.world().modifyBlockEntity(pos, TabletBlockEntity.class,
                be -> be.setApps(be.getApps().stream()
                        .map(a -> a.withActive(active))
                        .toList()));
    }
}
