package com.modpack.linktablet.client.screen;

import com.modpack.linktablet.client.AppView;
import com.modpack.linktablet.client.ClientPrefs;
import com.modpack.linktablet.client.UISounds;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.util.RandomSource;

/**
 * 💡 (1.8.0, unadvertised): "Lights" + a Redstone Lamp icon. A 5×5
 * panel of lamps; tapping one inverts it and its cross neighbors —
 * douse the whole panel in as few presses as possible. Boards are
 * generated by pressing random lamps from the solved state, so every
 * puzzle is solvable. Best = fewest moves, in {@link ClientPrefs}.
 */
public class LightsOutScreen extends ArcadeScreen {

    private static final int N = 5;
    private static final int CELL = 16;

    private static final int LAMP_ON = 0xFFF7C948;
    private static final int LAMP_ON_CORE = 0xFFFFE79A;
    private static final int LAMP_OFF = 0xFF2A2D33;
    private static final int LAMP_OFF_CORE = 0xFF35393F;

    private final RandomSource random = RandomSource.create();
    private final boolean[] lit = new boolean[N * N];
    private int moves;
    private boolean solved;
    private boolean newBest;

    public LightsOutScreen(AppView view, boolean returnToTablet) {
        super("lights", view, returnToTablet);
        scramble();
    }

    @Override
    protected int boardW() {
        return N * CELL;
    }

    @Override
    protected int boardH() {
        return N * CELL;
    }

    private void scramble() {
        java.util.Arrays.fill(lit, false);
        // Press random lamps from solved: always solvable, usually messy
        for (int i = 0; i < 9; i++) {
            press(random.nextInt(N * N));
        }
        // A lucky all-off scramble would be a zero-move win; nudge once
        if (allOff()) press(random.nextInt(N * N));
        moves = 0;
        solved = false;
        newBest = false;
    }

    private void press(int index) {
        int x = index % N;
        int y = index / N;
        toggle(x, y);
        toggle(x - 1, y);
        toggle(x + 1, y);
        toggle(x, y - 1);
        toggle(x, y + 1);
    }

    private void toggle(int x, int y) {
        if (x < 0 || x >= N || y < 0 || y >= N) return;
        lit[y * N + x] ^= true;
    }

    private boolean allOff() {
        for (boolean b : lit) {
            if (b) return false;
        }
        return true;
    }

    @Override
    public boolean mouseClicked(double mouseX, double mouseY, int button) {
        if (solved) {
            UISounds.page();
            scramble();
            return true;
        }
        int cx = (int) Math.floor((mouseX - boardX()) / CELL);
        int cy = (int) Math.floor((mouseY - boardY()) / CELL);
        if (cx >= 0 && cx < N && cy >= 0 && cy < N && button == 0) {
            press(cy * N + cx);
            moves++;
            UISounds.tick(lit[cy * N + cx] ? 1.5F : 1.1F);
            if (allOff()) {
                solved = true;
                newBest = submitBest(moves, true);
                UISounds.confirm();
            }
            return true;
        }
        return super.mouseClicked(mouseX, mouseY, button);
    }

    @Override
    public void render(GuiGraphics graphics, int mouseX, int mouseY, float partialTick) {
        super.render(graphics, mouseX, mouseY, partialTick);
        int best = best();
        renderCabinet(graphics, moves + (best > 0 ? " / " + best : ""));
        int bx = boardX();
        int by = boardY();
        for (int i = 0; i < N * N; i++) {
            int x = bx + (i % N) * CELL;
            int y = by + (i / N) * CELL;
            boolean on = lit[i];
            graphics.fill(x + 1, y + 1, x + CELL - 1, y + CELL - 1, on ? LAMP_ON : LAMP_OFF);
            graphics.fill(x + 4, y + 4, x + CELL - 4, y + CELL - 4,
                    on ? LAMP_ON_CORE : LAMP_OFF_CORE);
        }
        if (solved) {
            renderOverlay(graphics, "PANEL CLEAR",
                    (newBest ? "new best: " : "moves: ") + moves, "tap for a new board");
        }
    }
}
